### ISSUE TITLE
MediaSoupTest throw exception on Windows 10

### ISSUE THREAD

**Issue by universeroc** [CoSMoSoftware/KITE-Sample-Tests#58]
2020-05-09 11:05:21,071 INFO  - Creating web driver for {"app":false,"kind":"browser","logger":{"name":"org.webrtc.kite.config.client.Client","debugEnabled":true},"count":5,"clientIndex":0,"fullReset":false,"jsonConfig":{"headless":"false","browserName":{},"platform":{}},"capability":{"headless":false,"windowSize":"1920,1200","technologyPreview":false,"useFakeMedia":true,"flags":[],"extraCapabilities":{},"maxInstances":5,"gateway":"none"},"paas":{"availableSlots":0,"region":"NC","type":"local","url":"http://localhost:4444/wd/hub"},"name":"0","exclude":false,"browserSpecs":{"extension":"","driverString":"-Dwebdriver.chrome.driver=./chromedriver","profile":"","browserName":"chrome","deviceName":"unknown","platform":"WINDOWS"},"region":"NC"}
 2020-05-09 11:05:21,071 INFO  - Creating web driver for {"app":false,"kind":"browser","logger":{"name":"org.webrtc.kite.config.client.Client","debugEnabled":true},"count":5,"clientIndex":0,"fullReset":false,"jsonConfig":{"headless":"false","browserName":{},"platform":{}},"capability":{"headless":false,"windowSize":"1920,1200","technologyPreview":false,"useFakeMedia":true,"flags":[],"extraCapabilities":{},"maxInstances":5,"gateway":"none"},"paas":{"availableSlots":0,"region":"NC","type":"local","url":"http://localhost:4444/wd/hub"},"name":"2","exclude":false,"browserSpecs":{"extension":"","driverString":"-Dwebdriver.chrome.driver=./chromedriver","profile":"","browserName":"chrome","deviceName":"unknown","platform":"WINDOWS"},"region":"NC"}
 2020-05-09 11:05:21,071 INFO  - Creating web driver for {"app":false,"kind":"browser","logger":{"name":"org.webrtc.kite.config.client.Client","debugEnabled":true},"count":5,"clientIndex":0,"fullReset":false,"jsonConfig":{"headless":"false","browserName":{},"platform":{}},"capability":{"headless":false,"windowSize":"1920,1200","technologyPreview":false,"useFakeMedia":true,"flags":[],"extraCapabilities":{},"maxInstances":5,"gateway":"none"},"paas":{"availableSlots":0,"region":"NC","type":"local","url":"http://localhost:4444/wd/hub"},"name":"1","exclude":false,"browserSpecs":{"extension":"","driverString":"-Dwebdriver.chrome.driver=./chromedriver","profile":"","browserName":"chrome","deviceName":"unknown","platform":"WINDOWS"},"region":"NC"}
 五月 09, 2020 11:05:24 上午 org.openqa.selenium.remote.ProtocolHandshake createSession
信息: Detected dialect: W3C
五月 09, 2020 11:05:24 上午 org.openqa.selenium.remote.ProtocolHandshake createSession
信息: Detected dialect: W3C
五月 09, 2020 11:05:24 上午 org.openqa.selenium.remote.ProtocolHandshake createSession
信息: Detected dialect: W3C
SLF4J: A number (6) of logging calls during the initialization phase have been intercepted and are
SLF4J: now being replayed. These are subject to the filtering rules of the underlying logging system.
SLF4J: See also http://www.slf4j.org/codes.html#replay
2020-05-09 11:05:24,788 INFO  - Starting the execution of the test runners in parallel
 2020-05-09 11:05:24,790 INFO  - Start processing the TestRunner(DEFAULT) id 0 in 0ms
 2020-05-09 11:05:24,790 INFO  - Start processing the TestRunner(DEFAULT) id 2 in 0ms
 2020-05-09 11:05:24,790 INFO  - Start processing the TestRunner(DEFAULT) id 1 in 0ms
 2020-05-09 11:05:27,061 ERROR - Step broken:
   message = ***UNHANDLED EXCEPTION***
 This is a bug and must be fixed. The exception must be caught and thrown as KiteTestException
   trace = java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.openqa.selenium.support.pagefactory.internal.LocatingElementListHandler.invoke(LocatingElementListHandler.java:39)
        at com.sun.proxy.$Proxy4.get(Unknown Source)
        at io.cosmosoftware.kite.mediasoup.pages.MediasoupPage.videoIsPublishing(MediasoupPage.java:37)
        at io.cosmosoftware.kite.mediasoup.pages.MediasoupPage.load(MediasoupPage.java:59)
        at io.cosmosoftware.kite.mediasoup.steps.JoinVideoCallStep.step(JoinVideoCallStep.java:29)
        at io.cosmosoftware.kite.steps.TestStep.execute(TestStep.java:67)
        at io.cosmosoftware.kite.steps.TestStep.processTestStep(TestStep.java:307)
        at org.webrtc.kite.tests.TestRunner.call(TestRunner.java:182)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by ik3210** [comment]
hello, i have the same problem, anyone fix it?

**Comment by ik3210** [comment]
ConfigFileName:  getstats.mediasoup.config.json

"clients": [
    {
      "browserName": "chrome",
	  "version": "90",
      "platform": "localhost",
      "headless": false
    }
  ],
  "_browsers_list": [
    {
      "browserName": "chrome",
	  "version": "90",
      "platform": "localhost",
      "headless": true
    },
    {
      "browserName": "firefox",
	  "version": "88",
      "platform": "localhost",
      "headless": true
    }
  ]

RunCommand: 
cd D:\workspace\KITE-Sample-Tests-master\KITE-Mediasoup-Test
kite_r configs\getstats.mediasoup.config.json
